name: Build and Test
on: [push, pull_request]
jobs:
  run-tests:
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    steps:
      - name: Setup packages on Linux
        run: |
          sudo apt update
          sudo apt install gcc-arm-none-eabi ninja-build cmake libzmq3-dev libsocketcan-dev socat iproute2
          sudo apt install linux-modules-extra-$(uname -r)

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Build CSP for STM32
        run: |
          cmake -S ./ -B build -G Ninja && ninja -C build

      - name: Build CSP for Linux
        run: |
          cd ./src/libcsp 
          python3 ./examples/buildall.py --build-system=cmake
          cd ../../

      - name: Get Renode
        run: |
          wget -q https://github.com/renode/renode/releases/download/v1.15.3/renode-1.15.3.linux-portable.tar.gz
          mkdir renode && tar -xzf ./renode-1.15.3.linux-portable.tar.gz -C renode --strip-components=1

      - name: Run Test Client
        run: |
          ./renode/renode --disable-gui --hide-log stm32h753.resc > /dev/null 2>& 1 &
          sleep 5
          socat -d -d -d pty,raw,echo=0,link=/tmp/pty1 /tmp/uart > /dev/null 2>& 1 &
          sleep 5
          ./src/libcsp/build/examples/csp_client -k /tmp/pty1 -a 2 -C 10 -T 10 -v 2
          pkill renode
          pkill socat

      - name: Run Test Server
        run: |
          ./renode/renode --disable-gui --hide-log stm32h753.resc > /dev/null 2>& 1 &
          sleep 5
          socat -d -d -d pty,raw,echo=0,link=/tmp/pty1 /tmp/uart > /dev/null 2>& 1 &
          sleep 5
          ./src/libcsp/build/examples/csp_server -k /tmp/pty1 -a 2 -T 10 -v 2
          pkill renode
          pkill socat
